server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:financial-service}

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bds-financial-service-db}?options=-c%20timezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:BatDongScamSecretKeyForJWTTokenAtLeast256BitsLong!!}
  expiration: ${JWT_EXPIRATION:10800000}

stripe:
  api-key: ${STRIPE_API_KEY:default-key}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:default-secret}